[tool.poetry]
name         = "Bookshelf Scanner"
version      = "0.0.0"
description  = "Required packages for the final project for CS5330."
authors      = ["James Parkington <pongs.acreage.0o@icloud.com>"]
readme       = "README.md"
package-mode = false

[tool.poetry.dependencies]
python        = "^3.12.7"
duckdb        = "*"
matplotlib    = "*"
numpy         = "*"
opencv-python = "*"
pandas        = "*"
pytesseract   = "*"
ruamel-yaml   = "*"
scipy         = "*"
seaborn       = "*"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"