- name         : shadow_removal
  display_name : Shadow Removal
  parameters:
    - name         : shadow_kernel_size
      display_name : Shadow Kernel Size
      value        : 15
      min          : 3
      max          : 21
      step         : 2
      increase_key : K
    - name         : shadow_median_blur
      display_name : Shadow Median Blur
      value        : 21
      min          : 3
      max          : 99
      step         : 2
      increase_key : B

- name         : color_clahe
  display_name : Color CLAHE
  parameters:
    - name         : clahe_clip_limit
      display_name : CLAHE Clip Limit
      value        : 2.0
      min          : 0.5
      max          : 10.0
      step         : 0.5
      increase_key : H

- name         : bilateral_filter
  display_name : Bilateral Filter
  parameters:
    - name         : bilateral_diameter
      display_name : Bilateral Diameter
      value        : 9
      min          : 1
      max          : 25
      step         : 2
      increase_key : D
    - name         : bilateral_sigma_color
      display_name : Sigma Color
      value        : 75.0
      min          : 1.0
      max          : 150.0
      step         : 5.0
      increase_key : C
    - name         : bilateral_sigma_space
      display_name : Sigma Space
      value        : 75.0
      min          : 1.0
      max          : 150.0
      step         : 5.0
      increase_key : S

- name         : edge_detection
  display_name : Edge Detection
  parameters:
    - name         : canny_threshold1
      display_name : Canny Threshold 1
      value        : 50
      min          : 0
      max          : 255
      step         : 5
      increase_key : T
    - name         : canny_threshold2
      display_name : Canny Threshold 2
      value        : 150
      min          : 0
      max          : 255
      step         : 5
      increase_key : t

- name         : adaptive_thresholding
  display_name : Adaptive Thresholding
  parameters:
    - name         : adaptive_block_size
      display_name : Adaptive Block Size
      value        : 11
      min          : 3
      max          : 51
      step         : 2
      increase_key : B
    - name         : adaptive_c
      display_name : Adaptive C
      value        : 2
      min          : -10
      max          : 10
      step         : 1
      increase_key : C

- name         : contour_adjustments
  display_name : Contour Adjustments
  parameters:
    - name         : min_contour_area
      display_name : Min Contour Area
      value        : 1000
      min          : 100
      max          : 10000
      step         : 100
      increase_key : A
    - name         : max_contours
      display_name : Max Contours for OCR
      value        : 10
      min          : 1
      max          : 50
      step         : 5
      increase_key : M
    - name         : contour_approximation
      display_name : Contour Approximation
      value        : True
      min          : False
      max          : True
      step         : 1
      increase_key : P

- name         : ocr_settings
  display_name : OCR Settings
  parameters:
    - name         : ocr_confidence_threshold
      display_name : OCR Confidence Threshold
      value        : 0.3
      min          : 0.0
      max          : 1.0
      step         : 0.05
      increase_key : O