- name         : ocr
  display_name : OCR
  parameters:
    - name         : ocr_confidence_threshold
      display_name : OCR Confidence Threshold
      value        : 0.3
      min          : 0.0
      max          : 1.0
      step         : 0.1
      increase_key : R

- name         : shadow_removal
  display_name : Shadow Removal
  parameters:
    - name         : shadow_kernel_size
      display_name : Shadow Kernel Size
      value        : 15
      min          : 1
      max          : 45
      step         : 2
      increase_key : K
    - name         : shadow_median_blur
      display_name : Shadow Median Blur
      value        : 21
      min          : 1
      max          : 45
      step         : 2
      increase_key : B

- name         : color_clahe
  display_name : Color CLAHE
  parameters:
    - name         : clahe_clip_limit
      display_name : CLAHE Clip Limit
      value        : 2.0
      min          : 0.0
      max          : 10.0
      step         : 0.5
      increase_key : H

- name         : bilateral_filter
  display_name : Bilateral Filter
  parameters:
    - name         : bilateral_diameter
      display_name : Bilateral Diameter
      value        : 9
      min          : 1
      max          : 45
      step         : 2
      increase_key : D
    - name         : bilateral_sigma_color
      display_name : Sigma Color
      value        : 75.0
      min          : 0.0
      max          : 150.0
      step         : 5.0
      increase_key : G
    - name         : bilateral_sigma_space
      display_name : Sigma Space
      value        : 75.0
      min          : 0.0
      max          : 150.0
      step         : 5.0
      increase_key : S

- name         : edge_detection
  display_name : Edge Detection
  parameters:
    - name         : canny_threshold_1
      display_name : Canny Threshold 1
      value        : 50
      min          : 0
      max          : 255
      step         : 5
      increase_key : T
    - name         : canny_threshold_2
      display_name : Canny Threshold 2
      value        : 150
      min          : 0
      max          : 255
      step         : 5
      increase_key : U

- name         : adaptive_thresholding
  display_name : Adaptive Thresholding
  parameters:
    - name         : adaptive_block_size
      display_name : Adaptive Block Size
      value        : 11
      min          : 3
      max          : 45
      step         : 2
      increase_key : Z
    - name         : adaptive_c
      display_name : Adaptive C
      value        : 2
      min          : -10
      max          : 10
      step         : 1
      increase_key : C
