- name         : ocr
  display_name : OCR
  enabled      : true
  parameters   :
    - name         : ocr_confidence_threshold
      display_name : OCR Confidence Threshold
      value        : 0.5
      min          : 0.0
      max          : 1.0
      step         : 0.05
      increase_key : O

- name         : shadow_removal
  display_name : Shadow Removal
  enabled      : false
  parameters   :
    - name         : shadow_kernel_size
      display_name : Shadow Kernel Size
      value        : 23
      min          : 1
      max          : 45
      step         : 2
      increase_key : S
    - name         : shadow_median_blur
      display_name : Shadow Median Blur
      value        : 15
      min          : 1
      max          : 45
      step         : 2
      increase_key : M

- name         : color_clahe
  display_name : Color CLAHE
  enabled      : false
  parameters   :
    - name         : clahe_clip_limit
      display_name : CLAHE Clip Limit
      value        : 1.0
      min          : 0.0
      max          : 10.0
      step         : 0.5
      increase_key : H

- name         : brightness_adjustment
  display_name : Brightness Adjustment
  enabled      : false
  parameters   :
    - name         : brightness_value
      display_name : Brightness Value
      value        : 0
      min          : -50
      max          : 50
      step         : 5
      increase_key : B

- name         : contrast_adjustment
  display_name : Contrast Adjustment
  enabled      : false
  parameters   :
    - name         : contrast_value
      display_name : Contrast Value
      value        : 1.0
      min          : 0.1
      max          : 3.0
      step         : 0.1
      increase_key : C

- name         : image_rotation
  display_name : Image Rotation
  enabled      : false
  parameters   :
    - name         : rotation_angle
      display_name : Rotation Angle
      value        : 90
      min          : 0
      max          : 270
      step         : 90
      increase_key : R